#!/bin/bash
#gausah di recode ya
#kode warna
a='\033[1;31m'
b='\033[1;32m'
c='\033[1;33m'
d='\033[1;34m'
e='\033[1;35m'
f='\033[1;36m'
o='\033[0m'
clear
banner(){
echo -e """\033[1;32m
╔══════════════════════════════════════╗
║  𝕾𝖊𝖑𝖆𝖒𝖆𝖙 𝕯𝖆𝖙𝖆𝖓𝖌 𝕯𝖎 𝕿𝖔𝖔𝖑𝖘 𝕷𝖎𝖒𝖎𝖙       ║
╚══════════════════════════════════════╝
██     ██ ██▄   ▄██ ██ ████████               
██     ▄▄ ██▀█▄█▀██ ▄▄    ██  ╔═╗   ╔═╔═        
██     ██ ██  ▀  ██ ██    ██  ╚═╣╣ ╣╠═╠═╔═╗        
██████ ██ ██     ██ ██    ██    ╚╚═╝╚═╚═╣ ╣
╔══════════════════════════════════════════════╗
 ℂ𝕠𝕕𝕖 𝔹𝕪 𝕃𝕚𝕞𝕚𝕥ℚ𝕦𝕖𝕖𝕟ℙ𝕣𝕠𝕛𝕖𝕔𝕥                                             
 Github : https://github.com/LimitQueenProject
 YOuTube : Limit Queen Project
╚══════════════════════════════════════════════╝
"""
}

cek(){
termux-setup-storage
command -v exiftool > /dev/null 2>&1 || { echo -e >&2 "${b}exiftool belum terinstall silahkan ketik\n .${a} pkg install exiftool -y ${o}"; exit 1; }
command -v pv > /dev/null 2>&1 || { echo -e >&2 "pv belum terinstall silahkan ketik ,\n ${a} pkg install pv -y${o}"; exit 1; }
}


mulai(){
echo
read -p $'\033[1;33mSilahkan masukan lokasi gambar :\033[1;32m ' gambar
echo -e "${d}Mencoba untuk mengambil informasi... " | pv -qL 10
echo -e "${e}"
exiftool $gambar
echo -e "${o}Done"
read -p $'\033[1;36mMau lagi ga :\033[1;33m ' lagi
if [[ $lagi == "lagi" || $lagi == "y" || $lagi == "mau" || $lagi == "Y" || $lagi == "ya" ]]; then
clear
sleep 1.5
banner
mulai
else
echo -e "${o}"
exit
fi
}
banner
cek
mulai
